### ISSUE TITLE
User Help: Hopscotch

### ISSUE THREAD

**Issue by tercer** [vjdorazio/TwoRavens#30]
In the PSI Tool we added Hopscotch as a way to guide a new user through the steps they ought to tackle to use the system.  It gives these messages "a tour", that can be triggered by events and turned off when the user doesn't want to see any more.  Here are some examples:

<img width="850" alt="screen shot 2017-09-06 at 11 21 13 am" src="https://user-images.githubusercontent.com/2085037/30120212-33adbc04-92f6-11e7-9b5d-44793c258c2d.png">
<img width="685" alt="screen shot 2017-09-06 at 11 22 09 am" src="https://user-images.githubusercontent.com/2085037/30120215-3522a48c-92f6-11e7-83db-a90be9dcd6cf.png">

I'm thinking to add something like this to point the novice user to the things they can act on at different stages / modes.  I thought to experiment with the D3M mode, and then take any experience there and port back to the more general case for all TwoRavens users.

**Comment by raprasad** [comment]
Quick note on adding hopscotch files to the project:

1. Add the js/css files as needed to the repo's `/assets` directory
    - https://github.com/vjdorazio/TwoRavens/tree/master/assets
1. Read the js/css files by following the syntax on the index.html page:
    - https://github.com/vjdorazio/TwoRavens/tree/master/assets

Example:
  - if `hopscotch.min.js` was added the repo here:
     ```
     /assets/hopscotch/js/hopscotch.min.js
    ```
  - the line added to the `index.html` file would be :
   ```html
    <script src="{% static "hopscotch/js/hopscotch.min.js" %}"></script>

   ```

**Comment by tercer** [comment]
This was added in October 2017.
